[profile.default]
libs = ['lib']
solc_version = "0.8.21"   # Override for the solc version (setting this ignores `auto_detect_solc`)
evm_version = "paris"     # to prevent usage of PUSH0, which is not supported on all chains

optimizer = true
optimizer_runs = 200
test = 'src/test'